package com.tta.fitnessapplication.api

object ApiPath {
    // xmapp url
//    const val GETDATA = "BTL2023/getAllData.php"
//    const val LOGIN = "BTL2023/user/login.php/"
//    const val INSERT_USER = "BTL2023/user/insertUser.php"
//    const val USER_INFO = "BTL2023/user/getAllData.php"
//    const val UPDATE_USER = "BTL2023/user/update.php"
//    const val UPDATE_USER_PROGESS = "BTL2023user/update_progess.php"
//    const val FULLBODY = "BTL2023/exercise/fullbody/getAllData.php"
//    const val SELECT_FULLBODY = "BTL2023/exercise/fullbody/selectDay.php"
//    const val DEMO = "BTL2023XDjAzlDHSSsEEyxi/aggregatesDatasets"
//    const val EXERCISE = "BTL2023/exercise/exerciser/getAllData.php"
//    const val SELECT_EXERCISE = "BTL2023/exercise/exerciser/selectExercise.php"
//    const val VIDEO = "BTL2023/video/getAllData.php"
//    const val ARTICLE = "BTL2023/article/getAllData.php"
//    const val TOOL = "BTL2023/tool/getAllData.php"
//    const val HISTORY_BY_DATE = "BTL2023/history/getAllDataByDate.php"
//    const val HISTORY_BY_DATE_AND_TYPE = "BTL2023/history/getDataByDateAndType.php"
//    const val HISTORY_DOWNLOAD = "BTL2023/history/getAllData.php"
//    const val HISTORY_UPLOAD = "BTL2023/history/insertHistory.php"
//    const val INSERT_HISTORY = "BTL2023/history/insertHistory.php"
//    const val DELETE_HISTORY = "BTL2023/history/deleteHistory.php"
//    const val CATEGORY_FOOD = "BTL2023/meal/category/getAllCategory.php"
//    const val SUGGEST_FOOD = "BTL2023/meal/food/getSuggestFood.php"
//    const val FOOD_BY_TYPE = "BTL2023/meal/food/getFoodByType.php"
//    const val FOOD_BY_CATEGORY = "BTL2023/meal/food/getFoodByIdCategory.php"
//    const val FOOD_BY_ID = "BTL2023/meal/food/getFoodById.php"
//    const val MAP_API = "BTL2023/location/getValueMapApi.php"
//    const val LOCATION = "BTL2023/location/getLocationById.php"
//    const val BACK_UP = "BTL2023/user/getLastBackUpFile.php"
//    const val USER_BACK_UP = "BTL2023/user/update_back_up.php"
    // online url
    const val GETDATA = "/getAllData.php"
    const val LOGIN = "/user/login.php/"
    const val INSERT_USER = "/user/insertUser.php"
    const val USER_INFO = "/user/getAllData.php"
    const val UPDATE_USER = "/user/update.php"
    const val UPDATE_USER_PROGESS = "user/update_progess.php"
    const val FULLBODY = "/exercise/fullbody/getAllData.php"
    const val SELECT_FULLBODY = "/exercise/fullbody/selectDay.php"
    const val DEMO = "XDjAzlDHSSsEEyxi/aggregatesDatasets"
    const val EXERCISE = "/exercise/exerciser/getAllData.php"
    const val SELECT_EXERCISE = "/exercise/exerciser/selectExercise.php"
    const val VIDEO = "/video/getAllData.php"
    const val ARTICLE = "/article/getAllData.php"
    const val TOOL = "/tool/getAllData.php"
    const val HISTORY_BY_DATE = "/history/getAllDataByDate.php"
    const val HISTORY_BY_DATE_AND_TYPE = "/history/getDataByDateAndType.php"
    const val HISTORY_DOWNLOAD = "/history/getAllData.php"
    const val HISTORY_UPLOAD = "/history/insertHistory.php"
    const val INSERT_HISTORY = "/history/insertHistory.php"
    const val DELETE_HISTORY = "/history/deleteHistory.php"
    const val CATEGORY_FOOD = "/meal/category/getAllCategory.php"
    const val SUGGEST_FOOD = "/meal/food/getSuggestFood.php"
    const val FOOD_BY_TYPE = "/meal/food/getFoodByType.php"
    const val FOOD_BY_CATEGORY = "/meal/food/getFoodByIdCategory.php"
    const val FOOD_BY_ID = "/meal/food/getFoodById.php"
    const val MAP_API = "/location/getValueMapApi.php"
    const val LOCATION = "/location/getLocationById.php"
    const val BACK_UP = "/user/getLastBackUpFile.php"
    const val USER_BACK_UP = "/user/update_back_up.php"
    const val SEARCH_FOOD = "/meal/food/searchFood.php"
    //https://v1.nocodeapi.com/trantheanh/fit/XDjAzlDHSSsEEyxi/aggregatesDatasets?dataTypeName=steps_count
}